type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  firstName: String
  lastName: String
}

type Category @table {
  user: User!
  name: String!
  createdAt: Timestamp!
  description: String
}

type Expense @table {
  user: User!
  category: Category!
  amount: Float!
  transactionDate: Date!
  createdAt: Timestamp!
  description: String
}

type Budget @table {
  user: User!
  category: Category!
  amount: Float!
  startDate: Date!
  endDate: Date!
  createdAt: Timestamp!
  description: String
}